[package]
name = "steam-kit"
version = "0.1.0"
authors = ["JAD3N <me@jaden.bio>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num_enum = "0.5"
thiserror = "1.0"
regex = "1.5"
lazy_static = "1.4"